// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Z8q9IUlDEdfrFWe4bohzqfdgyKa3nq8',
    appId: '1:546096928466:web:3f9fa61d2493f18c67ff0b',
    messagingSenderId: '546096928466',
    projectId: 'zilifesaver',
    authDomain: 'zilifesaver.firebaseapp.com',
    databaseURL: 'https://zilifesaver-default-rtdb.firebaseio.com',
    storageBucket: 'zilifesaver.appspot.com',
    measurementId: 'G-GXMZFXNR9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxgb704juxjT2fLIQ03F76j6hWxcElR7g',
    appId: '1:546096928466:android:f4c64c0d9a737f5567ff0b',
    messagingSenderId: '546096928466',
    projectId: 'zilifesaver',
    databaseURL: 'https://zilifesaver-default-rtdb.firebaseio.com',
    storageBucket: 'zilifesaver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAu_UaFSuK909C6hRtRRdZk3uIbANZrTU',
    appId: '1:546096928466:ios:273b6b289124cd6067ff0b',
    messagingSenderId: '546096928466',
    projectId: 'zilifesaver',
    databaseURL: 'https://zilifesaver-default-rtdb.firebaseio.com',
    storageBucket: 'zilifesaver.appspot.com',
    iosClientId: '546096928466-co54t9apub7nojhsplj7mlc2elbj5hj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverSide',
  );
}
